-- auto Generated on 2023-04-25
-- DROP TABLE IF EXISTS order_refund_list;
CREATE TABLE order_refund_list
(
    id                                      VARCHAR(36) NOT NULL COMMENT '主键ID',
    create_by                               VARCHAR(36)     DEFAULT '' COMMENT '创建人',
    create_time                             DATETIME        DEFAULT null COMMENT '创建时间',
    update_by                               VARCHAR(36)     DEFAULT '' COMMENT '修改人',
    update_time                             DATETIME        DEFAULT null COMMENT '修改时间',
    `year`                                  INT(11)         DEFAULT -1 COMMENT '创建年',
    `month`                                 INT(11)         DEFAULT -1 COMMENT '创建月',
    `day`                                   INT(11)         DEFAULT -1 COMMENT '创建日',
    del_flag                                VARCHAR(1)      DEFAULT '0' COMMENT '删除状态（0，正常，1已删除）',
    order_sub_list_id                       VARCHAR(36)     DEFAULT '' COMMENT '子订单id（供应商/包裹）',
    order_list_id                           VARCHAR(50)     DEFAULT '' COMMENT '订单id（店铺订单/平台订单）',
    order_no                                VARCHAR(50)     DEFAULT '' COMMENT '订单号（店铺订单/平台订单）',
    order_type                              VARCHAR(11)     DEFAULT '' COMMENT '订单类型；0：普通订单；1：拼团订单；2：抢购订单；3：自选订单；4：兑换订单；数据字典：order_type；',
    order_good_record_id                    VARCHAR(50)     DEFAULT '' COMMENT '订单商品记录id',
    member_id                               VARCHAR(50)     DEFAULT '' COMMENT '会员id',
    sys_user_id                             VARCHAR(50)     DEFAULT '' COMMENT '店铺用户id/平台供应商用户id',
    refund_type                             VARCHAR(1)      DEFAULT '' COMMENT '退款类型 0=仅退款 1=退货退款 2=换货 关联字典：refund_type',
    refund_reason                           VARCHAR(1)      DEFAULT '' COMMENT '退款原因,关联字典：order_store_refund_reason',
    refund_explain                          VARCHAR(500)    DEFAULT '' COMMENT '后台商家拒绝退款理由',
    remarks                                 VARCHAR(500)    DEFAULT '' COMMENT '售后申请说明',
    `status`                                VARCHAR(1)      DEFAULT '0' COMMENT '售后状态 0=待处理 1=待买家退回 2=换货中（等待店铺确认收货） 3=退款中 4=退款成功 5=已拒绝 6=退款关闭 7=换货关闭 8=换货完成。 关联字典：order_refund_status',
    good_main_picture                       VARCHAR(1000)   DEFAULT '' COMMENT '订单商品主图相对地址（以json的形式存储多张）',
    good_list_id                            VARCHAR(50)     DEFAULT '' COMMENT '订单商品id（只做对象映射）',
    good_specification_id                   VARCHAR(50)     DEFAULT '' COMMENT '订单商品规格id（只做对象映射）',
    good_name                               VARCHAR(100)    DEFAULT '' COMMENT '商品名称',
    good_specification                      VARCHAR(500)    DEFAULT '' COMMENT '规格名称，按照顺序逗号隔开',
    refund_certificate                      VARCHAR(1000)   DEFAULT '' COMMENT '申请退款凭证图片，按照顺序逗号隔开',
    refund_price                            DECIMAL(20, 2) DEFAULT 0.00 COMMENT '申请退款金额',
    refund_amount                           DECIMAL(20, 2) DEFAULT 0.00 COMMENT '申请退款数量',
    is_platform                             VARCHAR(1)      DEFAULT '' COMMENT '0=店铺  1=平台',
    good_record_total                       DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品总计金额（小计）',
    good_record_actual_payment              DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品实付款',
    good_record_coupon                      DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品优惠卷优惠金额',
    good_record_gift_card_coupon            DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品礼品卡优惠金额',
    good_record_total_coupon                DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品总优惠金额',
    good_record_amount                      DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品购买数量',
    close_explain                           VARCHAR(1)      DEFAULT '' COMMENT '售后单关闭原因，关联字典 refund_close_explain',
    refused_explain                         VARCHAR(500)    DEFAULT '' COMMENT '商家拒绝原因',
    merchant_consignee_name                 VARCHAR(50)     DEFAULT '' COMMENT '退货/换货商家邮寄信息：商家收件人姓名',
    merchant_consignee_address              VARCHAR(500)    DEFAULT '' COMMENT '退货/换货商家邮寄信息：商家收件地址',
    merchant_consignee_phone                VARCHAR(50)     DEFAULT '' COMMENT '退货/换货商家邮寄信息：商家收件手机号',
    merchant_consignee_province_id          VARCHAR(50)     DEFAULT '' COMMENT '退货/换货商家邮寄信息：商家收件地址：省',
    merchant_consignee_city_id              VARCHAR(50)     DEFAULT '' COMMENT '退货/换货商家邮寄信息：商家收件地址：市',
    merchant_consignee_area_id              VARCHAR(50)     DEFAULT '' COMMENT '退货/换货商家邮寄信息：商家收件地址：区',
    buyer_logistics_company                 VARCHAR(20)     DEFAULT '' COMMENT '买家寄回物流公司；0：顺丰速运；1：圆通快递；2：申通快递；3：中通快递；4：韵达快递；5：天天快递；6：中国邮政；7：EMS邮政特快专递；8：德邦快递；对应数据字典：logistics_company；',
    buyer_tracking_number                   VARCHAR(100)    DEFAULT '' COMMENT '买家寄回快递单号',
    buyer_logistics_tracking                json COMMENT '买家寄回物流跟踪信息的json保存（每次查询的时候更新）',
    exchange_good_specification_id          VARCHAR(500)    DEFAULT '' COMMENT '买家换货商品规格id，逗号分隔',
    exchange_good_specification             VARCHAR(500)    DEFAULT '' COMMENT '买家换货规格名称，按照顺序逗号隔开',
    exchange_member_shipping_address        json COMMENT '买家换货：买家收货地址json',
    merchant_logistics_company              VARCHAR(20)     DEFAULT '' COMMENT '换货时卖家寄回：商家物流公司；0：顺丰速运；1：圆通快递；2：申通快递；3：中通快递；4：韵达快递；5：天天快递；6：中国邮政；7：EMS邮政特快专递；8：德邦快递；对应数据字典：logistics_company；',
    merchant_tracking_number                VARCHAR(100)    DEFAULT '' COMMENT '换货时卖家寄回：商家快递单号',
    merchant_logistics_tracking             json COMMENT '换货时卖家寄回：商家物流跟踪信息的json保存（每次查询的时候更新）',
    refund_json                             json COMMENT '退款json返回日志',
    actual_refund_balance                   DECIMAL(20, 2) DEFAULT 0.00 COMMENT '实际退款余额',
    actual_refund_price                     DECIMAL(20, 2) DEFAULT 0.00 COMMENT '实际退款现金（汇付微信）',
    actual_refund_gift_card_balance         DECIMAL(20, 2) DEFAULT 0.00 COMMENT '实际退还礼品卡金额',
    actual_refund_discount_welfare_payments DECIMAL(20, 2) DEFAULT 0.00 COMMENT '实际退还抵扣的福利金（专区商品）',
    welfare_payments_price                  DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品抵扣福利金价值（专区商品）',
    welfare_payments                        DECIMAL(20, 2) DEFAULT 0.00 COMMENT '订单商品抵扣福利金（专区商品）',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT 'order_refund_list';
